Tokens = {
    'ASSIGN': "=",
    'END': "END",
    'START': "Start",
    'COND': "cond",
    'RERUN': "rerun",
    'ADD': "+",
    'SUB': "-",
    'MUL': "*",
    'DIV': "/",
    'MOD': "%",
    'FLRDIV': "$",
    'GT': ">",
    'LT': "<",
    'GTE': ">=",
    'LTE': "<=",
    'EQ': "==",
    'NE': "!=",
    'OPEN': "(",
    'CLOSE': ")",
    'CODEBLOCKSTART': "{",
    'CODEBLOCKEND': "}",
}